### ISSUE TITLE
Compile not work.

### ISSUE THREAD

**Issue by ghost** [NukkitRu/LightChat#5]
Compile not work.... Fix please? @sdir01

**Comment by ZizzyZizzy** [comment]
I fixed the Nukkit dependency, but I can't find the source for MadPerms anywhere.

[ERROR] /usr/local/src/LightChat/src/main/java/nukkit/sdir01/xchatreloaded/listeners/ChatListener.java:[7,29] package me.imjack.permissions does not exist

**Comment by 27rogi** [comment]
@ZizzyZizzy, you can download it by this URL (http://forums.voxelwind.com/resources/madperms-permissions-plugin.9/).
